contato/urls.py
from django.urls import path
from contato import views
from django.conf.urls import include
app_name = 'contato'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    # contato CRUD
    path('contato/<int:contato_id>/detail/', views.contato, name='contato'),
    path('contato/create/', views.create, name='create'),
    path('contato/<int:contato_id>/update/', views.update, name='update'),
    path('contato/<int:contato_id>/delete/', views.delete, name='delete'),

    # user c
    path('user/create', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contato.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contato/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.



class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name
    

class Contato(models.Model):
    first_name = models.CharField(max_length=50)
    last_name0 = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    descripion = models.TextField(blank=True, verbose_name='Descrição')
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Categoria')

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)


    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name0}'

contato/forms.py
from django import forms
from django.core.exceptions import ValidationError
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation

class ContatoForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'classe-a classe-b', 'placeholder': "seu nome",}
        ), 
        label='primeiro nome',
        help_text="texto de ajuda para user",
    )
    # editei por conta proria
    last_name0 = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'classe-a classe-b', 'placeholder': "seu ultimo nome",}
        ), 
        label='Sobrenome',
    )
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'classe-a classe-b',}
        ), 
        label='Telefone',
    )
    #até aqui

    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        ), 
        required=False,
    )

    class Meta:
        model = models.Contato
        fields = (
            'first_name', 'last_name0', 'phone',
             'email', 'descripion', 'category', 'picture')
       # widgets = {
        #    'first_name': forms.TextInput(
         #       attrs={'class': 'classe-a classe-b', 'placeholder': "seu nome",}
          #  )
        #}
    def clean(self):
        cleaned_data = self.cleaned_data
        if cleaned_data == '123':
            self.add_error(
                'first_name',
                ValidationError(
                    'Mensagem de erro', code='invalid'
                )
                  )
    
        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name == 'ABC':
            self.add_error('first_name', ValidationError('não digite ABC', code='invalid'))
        return first_name
    


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )

    last_name = forms.CharField(
        required=True,
        min_length=3,
    )

    email = forms.EmailField(
        required=True,
    )

    class Meta():
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )
        
        return email


class ResgisterUpdateForm(forms.ModelForm):
     first_name = forms.CharField(
         min_length=2,
         max_length=50,
         required=True,
         help_text='Required.',
         error_messages={
             'min_length': 'Por favor, adicione mais que duas letras.'
         }
        )
     last_name = forms.CharField(
         min_length=2,
         max_length=50,
         required=True,
         help_text='Required.',
        
     )

     password1 = forms.CharField(
         label="Password",
         strip=False,
         widget=forms.PasswordInput(attrs={"autocomplete": 'new-password'}),
         help_text=password_validation.password_validators_help_text_html(),
         required=False,
     )
     password2 = forms.CharField(
         label="Password",
         strip=False,
         widget=forms.PasswordInput(attrs={"autocomplete": 'new-password'}),
         help_text='User the same password as before.',
         required=False,
     )
     class Meta():
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
            )

     def save(self, commit=True):
         cleaned_data = self.cleaned_data   
         user = super().save(commit=False)

         password = cleaned_data.get('password1')

         if password:
             user.set_password(password)

         if commit:
             user.save()
         return user

     def clean(self):
         password1 = self.cleaned_data.get('password1')
         password2 = self.cleaned_data.get('password2')

         if password1 or password2:
             if password1 != password2:
                 self.add_error(
                     'password2',
                     ValidationError('senhas não batem')
                 )
         return super().clean()
     

     def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )
        
        return email
     
     def clean_password1(self):
         password1 = self.cleaned_data.get('password1')

         if not password1:
             try:
                 password_validation.validate_password(password1)
             except ValidationError as errors:
                 self.add_error(
                     'password1', 
                     ValidationError(errors)
                 )
        
         return password1

contato/views/contato_forms.py
from django.shortcuts import render, redirect, get_object_or_404
from contato.forms import ContatoForm
from django.urls import reverse
from contato.models import Contato
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required(login_url='contato:login')
def create(request):

    form_action = reverse('contato:create')

    if request.method == 'POST':
        form = ContatoForm(request.POST, request.FILES)
        context = {
        'form': form,
        'form_action': form_action,
    }
        if form.is_valid():
            contato = form.save(commit=False)
            contato.owner = request.user
            contato.save()
            return redirect('contato:update', contato_id=contato.pk)

        return render(request, 'contato/create.html', context)

    context = {
        'form': ContatoForm(),
        'form_action': form_action,
    }
    return render(request, 'contato/create.html', context)



@login_required(login_url='contato:login')
def update(request, contato_id):
    contato = get_object_or_404(Contato, pk=contato_id, show=True, owner=request.user)
    form_action = reverse('contato:update', args=(contato_id,))

    if request.method == 'POST':
        form = ContatoForm(request.POST, request.FILES, instance=contato)
        context = {
        'form': form,
        'form_action': form_action,
    }
        if form.is_valid():
            contato = form.save()
            return redirect('contato:update', contato_id=contato.pk)

        return render(request, 'contato/create.html', context)

    context = {
        'form': ContatoForm(instance=contato),
        'form_action': form_action,
    }
    return render(request, 'contato/create.html', context)



@login_required(login_url='contato:login')
def delete(request, contato_id):
    contato = get_object_or_404(Contato, pk=contato_id, show=True, owner=request.user)

    confirmation = request.POST.get('confirmation', 'no')
    print(' confirmation',  confirmation)
    if confirmation == 'yes':
        contato.delete()
        return redirect('contato:index')
    return render(
        request,
        'contato/contato.html',
        {
            'contato': contato,
            'confirmation': confirmation,
        }
    )

contato/views/contato_views.py
from django.shortcuts import render, get_object_or_404, redirect
from contato.models import Contato
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    contatos = Contato.objects.filter(show=True).order_by('id')

    paginator = Paginator(contatos, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj, 
        'site_title': 'Contatos - '
    }

    return render(request, 'contato/index.html', context)


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contato:index')

    contatos = Contato.objects.filter(show=True)\
        .filter(Q(first_name__icontains=search_value) | Q(last_name0__icontains=search_value) | Q(phone__icontains=search_value) |
                Q(email__icontains=search_value))\
        .order_by('id')

    
    paginator = Paginator(contatos, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj, 
        'site_title': 'Search - '
    }

    return render(request, 'contato/index.html', context)




def contato(request, contato_id):
   # single_contato = Contato.objects.filter(pk=contato_id).first()
    single_contato = get_object_or_404(Contato, pk=contato_id, show=True)

    site_title = f'{single_contato.first_name} {single_contato.last_name0} - '

    context = {
        'contato': single_contato, 
        'site_title': site_title,
    }

    return render(request, 'contato/contato.html', context)

contato/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from contato.forms import RegisterForm, ResgisterUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

def register(request):
    form = RegisterForm()

    messages.info(request, 'slaaar')
    messages.warning(request, 'slaaar')
    messages.error(request, 'slaaar')

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario registrado')
            return redirect('contato:index')

    return render(
        request,
        'contato/register.html',
        {
            'form': form
        }
    )


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
           # messages.success('logado com sucesso')
            print(user)
            auth.login(request, user)
            return redirect('contato:index')
        else:
            messages.error(request, 'login inválido')

    return render(
        request, 
        'contato/login.html',
        {
            'form': form
        }
    )
@login_required(login_url='contato:login')
def user_update(request):
     form = ResgisterUpdateForm(instance=request.user)

     if request.method != 'POST':
         
        return render(
            request,
            'contato/user_update.html',
            {
                'form': form
            }
        )
     form = ResgisterUpdateForm(data=request.POST, instance=request.user)

     if not form.is_valid():
         return render(
            request,
            'contato/user_update.html',
            {
                'form': form
            }
        )
     form.save()
     return redirect('contato:user_update')

@login_required(login_url='contato:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contato:login')

contato/templates/contato/contato.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contato">
    <h1 class="single-contato-name">
      {{ contato.first_name }} {{ contato.last_name0 }}
    </h1>

    <p><b>ID:</b> {{ contato.id}}</p>
    <p><b>E-mail:</b> {{ contato.email }}</p>
    <p><b>Telefone:</b> {{ contato.phone }}</p>
    <p><b>Descrição:</b> {{ contato.descripion }}</p>
    <p><b>Categoria:</b> {{ contato.category }}</p>

    {% if contato.picture %}
      <p>
        <img src="{{ contato.picture.url }}" alt="{{ contato.first_name }} {{ contato.last_name0 }}">
      </p>
    {% endif %}

    {% if user == contato.owner %}
      <div class="contact-links">
        <a class='btn btn-link' href="{% url "contato:update" contato.id %}">Atualizar</a>

        <form action="{% url "contato:delete" contato.id %}" method="POST">
          {% csrf_token %}


          {% if confirmation == 'no' %}
            <input type="hidden" name="confirmation" value='yes'>
            <button class="btn btn-link btn-delete" type="submit">Confirmar deleção</button>
          {% else %}
            <button class="btn btn-link btn-delete" type="submit">Deletar</button>
          {% endif %}
        
        </form>
      </div>
    </div>
  {% endif %}
{% endblock content %}

contato/templates/contato/create.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="form-wrapper">

    <h2>Criar Contato</h2>

    <form 
        action=""
        method="POST"
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help-text">
                            {{ field.help_text }}
                        </p>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
    
        {% if form.non_field_errors %}
            <div class="form-content">
                <div class="form-group">
                <div class="menssage erro">
                    {{ form.non_field_errors }}
                </div>
            </div> 
            </div>
        {% endif %}


        <div class="form-content">
        <div class="form-group">
            <button class="btn" type="submit">Send</button>
        </div>
        </div>

    </form>
    </div>
{% endblock content %}

contato/templates/contato/index.html
{% extends "global/base.html" %}


{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption ">
                Contatos
            </caption>

            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First name</th>
                    <th class="table-header">Last name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>
            <tbody>
                {% for contato in page_obj %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'contato:contato' contato.id %}">
                                {{contato.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contato.first_name}}
                        </td>
                        <td class="table-cel">
                            {{contato.last_name0}}
                        </td>
                        <td class="table-cel">
                            {{contato.phone}}
                        </td>
                        <td class="table-cel">
                            {{contato.email}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contato">
    <h1 class="single-contato-name">
        Nenhum contato encontrado.
    </h1>
  </div>
{% endif %}
{% endblock content %}

contato/templates/contato/login.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="form-wrapper">

    <h2>Login  {{ user }}  </h2>

        {% if user.is_authenticated %}
        <p>
            você fez login como {{ user }}
            clique <a href="{% url "contato:logout" %}"> aqui </a> 
            para sair
        </p>
        {% else %}

       
        {% include "contato/partials/_user-form.html" %}
        {% endif %}

    </div>
{% endblock content %}

contato/templates/contato/register.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="form-wrapper">

    <h2>Register</h2>

    <form 
        action="{{ form_action }}"
        method="POST"
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        
        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help-text">
                            {{ field.help_text }}
                        </p>
                    {% endif %}

                </div>
            {% endfor %}
            </div>
    
        {% if form.non_field_errors %}
            <div class="form-content">
                <div class="form-group">
                <div class="menssage erro">
                    {{ form.non_field_errors }}
                </div>
            </div> 
            </div>
        {% endif %}


        <div class="form-content">
        <div class="form-group">
            <button class="btn" type="submit">Send</button>
        </div>
        </div>

    </form>
    </div>
{% endblock content %}

contato/templates/contato/user_update.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="form-wrapper">

    <h2>Atualização de dados</h2>

        {% include "contato/partials/_user-form.html" %}

    </div>
{% endblock content %}